#!/bin/bash
pwd
press
control x and control
0-current_working_directory
press
control x and control c
ls -a
chmod u+x 0-current_working_directory
git config --global user.email "jacqueslee0016@gmail.com"
git config --global user.name "BergPadda00"
git add .
git commit -m '1-listit'
git push
qs